name: Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Vue to Github Pages
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: wenjinghuan999
        reponame: dyson-sphere-program-recipe
        token: ${{ secrets.GITHUB_TOKEN }}
        cname: dsp-recipe.wenjinghuan.cn
